apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/<DEIN_GH_USER>/flux-podinfo-lab
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/podinfo/overlays/production
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: podinfo
