apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x.x"        # optional
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: LoadBalancer
      ingressClassResource:
        name: nginx
        default: true
